FROM node:22-alpine
WORKDIR /app

# Install openssl for self-signed cert generation
RUN apk add --no-cache openssl

# Copy manifests first (better layer caching)
COPY package.json package-lock.json* ./
RUN if [ -f package-lock.json ]; then npm ci --omit=dev; else npm install --omit=dev; fi

# App files (assumes server_https.js exists in project root)
COPY . .

# Add helper script into image
COPY bin/generate-certs.sh /app/bin/generate-certs.sh
RUN chmod +x /app/bin/generate-certs.sh

ENV NODE_ENV=production \
    CERT_DIR=/app/certs \
    CERT_HOSTNAMES="localhost 127.0.0.1"

EXPOSE 3000 3443

# Default command still the HTTPS server; certs will be generated by init service
CMD ["node", "server_https.js"]
